apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: tickets-microservice
build:
  artifacts:
    - image: auth-service-image
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: tickets-service-image
      context: tickets
      docker:
        dockerfile: Dockerfile
    - image: client-service-image
      context: client
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - infra/k8s/**/*.yaml
    - infra/k8s/ingress.yaml
