apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: tickets-microservice
build:
  artifacts:
    - image: auth-service-image
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth-service/service.yaml
    - infra/k8s/auth-service/mongodb.yaml
    - infra/k8s/auth-service/secret.yaml
    - infra/k8s/ingress.yaml
