apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: tickets-microservice
build:
  artifacts:
    - image: auth-service-image
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth.yaml
    - infra/k8s/ingress.yaml
portForward:
  - resourceType: service
    namespace: ingress-nginx
    resourceName: ingress-nginx-controller
    port: 80
    localPort: 3000
