apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://ticketz.dev"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Origin, X-Requested-With, Content-Type, Accept"
  labels:
    name: auth
spec:
  tls:
    - hosts:
        - api.ticketz.dev
      secretName: tls-secret
  rules:
    - host: api.ticketz.dev
      http:
        paths:
          - pathType: Prefix
            path: /api/users/?(.*)
            backend:
              service:
                name: auth
                port:
                  number: 3000
    
    - host: api.ticketz.dev
      http:
        paths:
          - pathType: Prefix
            path: /api/tickets/?(.*)
            backend:
              service:
                name: tickets
                port:
                  number: 3000

    - host: ticketz.dev
      http:
        paths:
          - pathType: Prefix
            path: /?(.*)
            backend:
              service:
                name: client
                port:
                  number: 3000
